### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-website#27]
> The links of the installer for Linux are broken on https://buttercup.pw/ and the link to receive a donation is broken too https://opencollective.com/buttercup-desktop/donate

Originally by @regoremor on buttercup/buttercup-desktop#372

**Comment by regoremor** [comment]
![screenshot from 2017-10-23 11-19-45](https://user-images.githubusercontent.com/9708927/31897440-642e7676-b7e4-11e7-8bc9-f79659a6f35a.png)

**Comment by perry-mitchell** [comment]
Thanks @regoremor!
