### ISSUE TITLE
Add feature to clear clipboard after a few seconds like in KeePass

### ISSUE THREAD

**Issue by tridaxide** [buttercup/buttercup-website#35]
Currently the password stays in the clipboard, which means if the contents of the clipboard is not cleared out or replaced by a different item, then the password can easily be revealed by pasting if the user does not replace clipboard contents after password copying. Automatic clearing of clipboard contents after a few seconds (which can be changed in a setting) will ensure safety of the password.

**Comment by sallar** [comment]
Hi @tridaxide, this is currently available in Buttercup Desktop. In which app do you have this issue?

**Comment by tridaxide** [comment]
Well I tried waiting for a couple of seconds to a minute but the password still stays in the clipboard. I also cannot find a setting for it.

**Comment by perry-mitchell** [comment]
As my colleague mentioned, this issue doesn't belong on the website repo. You can find the relevant issue on the desktop application here: ~~buttercup/buttercup-desktop#134~~

EDIT: My mistake, this feature was already added here: buttercup/buttercup-desktop#234

It does seem that it was only added on shortcut keys, and not on right-click. Could you confirm this @sallar? If so, we'll need to add the clearing functionality for right-click as well..
