### ISSUE TITLE
Buttercup website featured on beautifulopen.com

### ISSUE THREAD

**Issue by lukechilds** [buttercup/buttercup-website#39]
Just opening this issue you to let you know I submitted the Buttercup website to [Beautiful Open](http://beautifulopen.com) and it got featured today.

<img width="682" alt="screen shot 2018-11-01 at 10 38 21 pm" src="https://user-images.githubusercontent.com/2123375/47862149-0a23a880-de27-11e8-8e1b-e9ae20134d29.png">

**Comment by perry-mitchell** [comment]
🎉🎉🎉 That's amazing! 🎉🎉🎉

Thank you @lukechilds - That's great news!
