### ISSUE TITLE
S3 Seems to be misconfigured

### ISSUE THREAD

**Issue by vikaspotluri123** [buttercup/buttercup-website#46]
Hey there :wave:

I was just poking around in buttercup desktop, and clicked help->privacy policy, I got a cloudfront 403 error in Chrome. 

The URL is correct (https://buttercup.pw/privacy/), and I can verify this by going to the buttercup home page, and clicking privacy policy from there. 

Directly accessing the privacy policy page (i.e. editing the url when you're currently on the pp page and pressing <kbd>enter</kbd> to trigger a fresh request) also returns a 403

**Comment by sallar** [comment]
Hi @vikaspotluri123, we tried to fix this and it seems it's doing ok now. I'm gonna close this, but let us know if it started working now.

**Comment by vikaspotluri123** [comment]
Works on my end as well 👍
