### ISSUE TITLE
Download link for windows is broken

### ISSUE THREAD

**Issue by ChangJoo-Park** [buttercup/buttercup-website#50]
@sallar 

![image](https://user-images.githubusercontent.com/1451365/67872670-a8029e00-fb75-11e9-9b58-8a0d4c16e000.png)

this is link in website (auto generated)
https://github.com/buttercup/buttercup-desktop/releases/download/v1.17.2/buttercup-desktop-setup-1.17.2.exe

this is link in release
https://github.com/buttercup/buttercup-desktop/releases/download/v1.17.2/Buttercup-Setup-1.17.2.exe

this setup file need to change to buttercup-desktop-setup-1.17.2.exe

**Comment by theoricher** [comment]
I have solve this issue on pull request #51 :)

**Comment by theoricher** [comment]
@sallar You can close this issue :)
