### ISSUE TITLE
github 404 on Win Desktop link. 

### ISSUE THREAD

**Issue by GravisTechGregB** [buttercup/buttercup-website#71]
![TinyTake27-03-2024-11-29-13](https://github.com/buttercup/buttercup-website/assets/132407936/720dac03-0591-42ca-a118-25dfa659e484)

**Comment by Oxalin** [comment]
Not reproducible anymore. On new releases, sometimes the binaries are not yet available on GitHub even though the links are updated.

**Comment by perry-mitchell** [comment]
I think there's still something wrong here. It shows the latest version even when it's in draft mode. I suspect it's taking it from the tag, which is wrong. It should only show the most recent **stable** _release_.
